"""
app.py
------
NephroScan AI — Hugging Face Spaces Gradio Interface
Diagnostic CT Kidney Disease Classification using EfficientNetB0.
"""

from pathlib import Path
import gradio as gr
from PIL import Image

try:
    import spaces
    has_spaces = True
except ImportError:
    has_spaces = False

from src.inference.predict import predict_image, CLASS_NAMES

# Clinical descriptions and reference findings
CLINICAL_DETAILS = {
    "Normal": {
        "badge": "🟢 Normal Renal CT",
        "summary": "Normal renal parenchyma demonstrated with preserved corticomedullary differentiation. No focal calculi, cystic lesions, or space-occupying neoplasms detected.",
        "findings": "Homogeneous renal cortex and medulla with smooth renal contours. Renal sinus fat and collecting system appear anatomically unremarkable.",
    },
    "Cyst": {
        "badge": "🟡 Renal Cyst Detected",
        "summary": "Well-circumscribed fluid-attenuation lesion identified. Consistent with Bosniak Category benign/simple or complex renal cystic lesion.",
        "findings": "Typically exhibits smooth thin walls, homogeneous water-density (<20 Hounsfield Units), with lack of internal calcification or pathological contrast enhancement.",
    },
    "Stone": {
        "badge": "🟠 Nephrolithiasis (Renal Calculi)",
        "summary": "Hyperdense calcified focus identified within the renal calyces or pelviureteric junction, indicative of nephrolithiasis / urolithiasis.",
        "findings": "Radio-opaque density (>200-400 HU on unenhanced CT). Evaluation recommended for secondary signs including hydronephrosis or perinephric stranding.",
    },
    "Tumor": {
        "badge": "🔴 Space-Occupying Cortical Mass",
        "summary": "Space-occupying solid or heterogeneous renal cortical mass detected, suspicious for Renal Cell Carcinoma (RCC) or oncocytoma.",
        "findings": "Characterized by soft-tissue attenuation, irregular margins, internal heterogeneity, necrosis, or vascular invasion. Immediate formal radiologic staging recommended.",
    },
}

DISCLAIMER_TEXT = (
    "⚠️ **Medical Safety Notice:** This application is strictly an educational and research "
    "demonstration. It is **NOT** a certified medical diagnostic device (FDA/CE-cleared) and "
    "must **never** be used for clinical decision-making or patient diagnosis."
)


def _predict_handler(image: Image.Image):
    """Run model inference on the uploaded CT slice and return probabilities and clinical report."""
    if image is None:
        return None, "### Please upload an image to analyze."

    try:
        result = predict_image(image)
        prediction = result["prediction"]
        confidence = result["confidence"]
        probabilities = result["probabilities"]

        details = CLINICAL_DETAILS.get(prediction, {})
        badge = details.get("badge", prediction)
        summary = details.get("summary", "")
        findings = details.get("findings", "")

        report_md = f"""
### Diagnostic Assessment: {badge}
- **Primary Prediction:** **{prediction}** ({confidence * 100:.2f}% Confidence)
- **Clinical Summary:** {summary}
- **Radiological Reference:** {findings}

---
*Generated by NephroScan AI Deep Learning Inference Engine (EfficientNetB0).*
"""
        return probabilities, report_md

    except Exception as exc:
        return None, f"**Error during inference:** {exc}"


if has_spaces:
    @spaces.GPU
    def classify_ct_scan(image: Image.Image):
        return _predict_handler(image)
else:
    def classify_ct_scan(image: Image.Image):
        return _predict_handler(image)


# Define sample images if available
SAMPLE_DIR = Path("app/samples")
examples = []
if SAMPLE_DIR.exists():
    sample_files = [
        SAMPLE_DIR / "normal_sample.jpg",
        SAMPLE_DIR / "cyst_sample.jpg",
        SAMPLE_DIR / "stone_sample.jpg",
        SAMPLE_DIR / "tumor_sample.jpg",
    ]
    examples = [[str(f)] for f in sample_files if f.exists()]

# Custom CSS for modern styling
custom_css = """
#main-container { max-width: 1000px; margin: 0 auto; }
.header-title { text-align: center; margin-bottom: 5px; color: #1e3a5f; }
.header-sub { text-align: center; color: #5a6e85; margin-bottom: 20px; font-size: 1.05rem; }
.disclaimer-box { background: #fff8e1; border-left: 5px solid #ffa000; padding: 12px 16px; border-radius: 4px; margin-bottom: 20px; }
"""

# Build Gradio Interface
with gr.Blocks(css=custom_css, title="NephroScan AI — CT Kidney Disease Classifier") as demo:
    with gr.Column(elem_id="main-container"):
        gr.Markdown("# 🫁 NephroScan AI: CT Kidney Disease Classification", elem_classes=["header-title"])
        gr.Markdown(
            "Deep Learning Diagnostic System powered by **EfficientNetB0** for automated classification of Axial Kidney CT Slices (**Normal, Cyst, Stone, Tumor**).",
            elem_classes=["header-sub"],
        )

        with gr.Row(elem_classes=["disclaimer-box"]):
            gr.Markdown(DISCLAIMER_TEXT)

        with gr.Row():
            with gr.Column(scale=1):
                input_image = gr.Image(type="pil", label="Upload Kidney CT Scan Image", sources=["upload", "clipboard"])
                predict_btn = gr.Button("🔍 Analyze CT Scan", variant="primary", size="lg")
                
                if examples:
                    gr.Examples(
                        examples=examples,
                        inputs=[input_image],
                        label="1-Click CT Scan Sample Presets",
                    )

            with gr.Column(scale=1):
                output_label = gr.Label(num_top_classes=4, label="Class Probabilities")
                output_report = gr.Markdown(label="Clinical Insight Report")

        predict_btn.click(
            fn=classify_ct_scan,
            inputs=[input_image],
            outputs=[output_label, output_report],
        )

if __name__ == "__main__":
    demo.launch()
